#!/bin/bash

install_path=$1
service=$2
port=$3
domain=$4

if [ -z "$service" ];then
    echo "Usage: $0 install_path service [port [domain]]"
    exit 1
fi

if [ -z "$port" ];then
    port=2539
fi

if [ -z "$domain" ];then
    domain=localhost
fi

echo $install_path
echo $service
echo $port
echo $domain

cp conf/* $install_path/nginx/conf/
mkdir -p $install_path/nginx/services

sed "s/{service}/$service/g" tmpl/service.conf > $install_path/nginx/services/$service.conf
sed -i "s/{port}/$port/g" $install_path/nginx/services/$service.conf
sed -i "s/{domain}/$domain/g" $install_path/nginx/services/$service.conf

mkdir -p $install_path/nginx/services/$service
cp -rf tmpl/service/* $install_path/nginx/services/$service/
